#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_LOG=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_RESET_ON_FATAL_ERROR=n

# STEP 1.1 - Enable Kconfigs for SPI and GPIO
CONFIG_GPIO=y
#CONFIG_NRFX_GPIOTE=y

CONFIG_NRFX_SPIM1=y


CONFIG_TFM_SECURE_UART=n

CONFIG_TFM_LOG_LEVEL_SILENCE=y

CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=256